# Generated by Django 5.2.7 on 2025-11-25 09:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('chance_to_trigger', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.PositiveIntegerField(help_text='Relative chance among siblings. Higher = more likely.', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_terminal', models.BooleanField(default=False, help_text='If true, branch stops here.')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='events.event')),
                ('parent', models.ForeignKey(blank=True, help_text='Root scenarios have no parent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='events.scenario')),
            ],
        ),
    ]
